######################################################################
# Automatically generated by qmake (3.0) Mon Mar 28 00:33:46 2016
######################################################################

TEMPLATE = app
TARGET = wav2dat
INCLUDEPATH += .
DESTDIR = bin

# Input
SOURCES += wav2dat.cpp
