#include <QCoreApplication>
#include <QString>
#include <QDebug>
#include <QFile>
#include <QFileInfo>
#include <QTextStream>

#ifndef VERSION
#define VERSION "0.0.0"
#endif

int main (int argc, char * argv[])
{
    int rows = 8, cols = 64;
    quint32 row = 0;
    quint32 rowinc = 256/rows;
    quint32 colinc = 512/cols;

    QCoreApplication app(argc, argv);
    QCoreApplication::setOrganizationName("LameStation LLC");
    QCoreApplication::setOrganizationDomain("www.lamestation.com");
    QCoreApplication::setApplicationVersion(VERSION);
    QCoreApplication::setApplicationName(QObject::tr("wav2dat"));

	quint32 c;
	quint32 w;

	quint32 samplecount = 0;

	if (argc < 2) return 1;

    QString filename = argv[1];
    QFileInfo fi(filename);
    QString outputfilename = fi.path() + "/wav_" + fi.completeBaseName() + ".spin";

    QFile infile(filename);
    QFile outfile(outputfilename);

    if (!infile.open(QIODevice::ReadOnly))
    {
        qDebug() << "Error reading input:" << filename;
        return 1;
    }

    if (!outfile.open(QIODevice::WriteOnly))
    {
        qDebug() << "Error writing output:" << outputfilename;
        return 1;
    }

    QByteArray input  = infile.readAll();

	quint32 datasize = input.size() - 44;
    quint32 bitdepth = input[34];
	quint32 sourcesamples = datasize/(bitdepth/8);
    quint32 targetsamples = 512;
    quint32 sampleinc = (sourcesamples << 8)/targetsamples;

//    qDebug() << "  file size:" << input.size() << "B";
//    qDebug() << "  data size:" << datasize << "B";
//    qDebug() << "  bit depth:" << bitdepth << "b";
//    qDebug() << "   src size:" << sourcesamples << "B";
//    qDebug() << "   dst size:" << targetsamples << "B";
//    qDebug() << " sample inc:" << (sampleinc >> 8) << "." << (sampleinc & 0xFF)*100/256;

    QList<quint32> samples;
    for (quint32 i = 0; ((i >> 8) < sourcesamples) && (samplecount < targetsamples); i += (sourcesamples << 8)/targetsamples)
    {
    	c = input[44 + (i >> 7) + 1];             // 8 bit = i >> 8
    	w = (qint8) c + 128;
        samples.append(w);
    	samplecount++;
    }

    qDebug() << samples.size();

    // generate output

    QString output;
    QTextStream stream(&output);

    stream << "' *" << QString(cols, '*') << "\n";
    stream << "' " << fi.fileName() << "\n"
           << "' generated by wav2dat " << qApp->applicationVersion() << "\n";
    stream << "' *" << QString(cols, '*') << "\n\n";

    stream     << "' -" << QString(cols, '-') << "\n";
    for (int i = 0; i < rows; i++) 
    {
        QString p(cols, ' ');

        for (int j = 0; j < samples.size(); j += colinc)
        {
            if ((samples[j] >= row) && (samples[j] < (row + rowinc)))
                p[j / colinc] = 'o';//samples[j];
        }

        row += rowinc;

        stream << "' |" << p << "\n";
    }

    stream     << "' -" << QString(cols, '-') << "\n";
    stream << "\n";





    stream  << "PUB Addr\n"
            << "    return @wav_data\n\n"
            << "DAT\n\n"
            << "wav_data\n";

    for (int i = 0; i < 512; i++)
    {
    	if (i % 16 == 0)    stream << "\nbyte    ";
        stream << QString("%1").arg((quint8) samples[i], 3);
        if (i % 16 != 15)   stream << ", ";
    }

    stream << "\n";

    qDebug() << qPrintable(output);

    QTextStream outstream(&outfile);
    outstream << output;
    outfile.close();

    return 0;
}
